from __future__ import annotations

TECH_DATABASE: list[dict] = [
    {'name': 'JavaScript', 'category': 'language', 'patterns': ['\\.js$', '\\.jsx$', '\\.mjs$', '\\.cjs$', 'package\\.json'], 'confidence': 95},
    {'name': 'TypeScript', 'category': 'language', 'patterns': ['\\.ts$', '\\.tsx$', '\\.mts$', '\\.cts$', 'tsconfig\\.json'], 'confidence': 95},
    {'name': 'Python', 'category': 'language', 'patterns': ['\\.py$', '\\.pyw$', '\\.pyx$', 'requirements\\.txt', 'setup\\.py', 'Pipfile'], 'confidence': 95},
    {'name': 'Java', 'category': 'language', 'patterns': ['\\.java$', '\\.class$', '\\.jar$', 'pom\\.xml', 'build\\.gradle'], 'confidence': 90},
    {'name': 'Rust', 'category': 'language', 'patterns': ['\\.rs$', '\\.rlib$', 'Cargo\\.toml'], 'confidence': 90},
    {'name': 'Go', 'category': 'language', 'patterns': ['\\.go$', 'go\\.mod', 'go\\.sum'], 'confidence': 90},
    {'name': 'C++', 'category': 'language', 'patterns': ['\\.cpp$', '\\.cxx$', '\\.cc$', '\\.c++$', '\\.hpp$', '\\.hxx$', '\\.hh$', '\\.h\\+\\+$', 'CMakeLists\\.txt'], 'confidence': 85},
    {'name': 'C', 'category': 'language', 'patterns': ['\\.c$', '\\.h$'], 'confidence': 85},
    {'name': 'Ruby', 'category': 'language', 'patterns': ['\\.rb$', '\\.erb$', '\\.rake$', 'Gemfile', 'Rakefile'], 'confidence': 85},
    {'name': 'PHP', 'category': 'language', 'patterns': ['\\.php$', '\\.phtml$', '\\.php3$', '\\.php4$', '\\.php5$', 'composer\\.json'], 'confidence': 85},
    {'name': 'Swift', 'category': 'language', 'patterns': ['\\.swift$', 'Package\\.swift'], 'confidence': 85},
    {'name': 'Kotlin', 'category': 'language', 'patterns': ['\\.kt$', '\\.kts$', '\\.ktm$'], 'confidence': 85},
    {'name': 'C#', 'category': 'language', 'patterns': ['\\.cs$', '\\.csproj$', '\\.sln$'], 'confidence': 85},
    {'name': 'Scala', 'category': 'language', 'patterns': ['\\.scala$', '\\.sc$', 'build\\.sbt'], 'confidence': 80},
    {'name': 'Dart', 'category': 'language', 'patterns': ['\\.dart$', 'pubspec\\.yaml'], 'confidence': 80},
    {'name': 'R', 'category': 'language', 'patterns': ['\\.r$', '\\.R$', '\\.rda$', '\\.rds$'], 'confidence': 80},
    {'name': 'Shell', 'category': 'language', 'patterns': ['\\.sh$', '\\.bash$', '\\.zsh$', '\\.fish$'], 'confidence': 80},
    {'name': 'HTML', 'category': 'language', 'patterns': ['\\.html$', '\\.htm$', '\\.xhtml$', '\\.ejs$', '\\.hbs$', '\\.handlebars$', '\\.mustache$'], 'confidence': 75},
    {'name': 'CSS', 'category': 'language', 'patterns': ['\\.css$', '\\.scss$', '\\.sass$', '\\.less$', '\\.styl$'], 'confidence': 75},
    {'name': 'SQL', 'category': 'language', 'patterns': ['\\.sql$'], 'confidence': 70},
    {'name': 'Lua', 'category': 'language', 'patterns': ['\\.lua$'], 'confidence': 80},
    {'name': 'Julia', 'category': 'language', 'patterns': ['\\.jl$'], 'confidence': 80},
    {'name': 'Objective-C', 'category': 'language', 'patterns': ['\\.m$', '\\.mm$'], 'confidence': 80},
    {'name': 'Perl', 'category': 'language', 'patterns': ['\\.pl$', '\\.pm$', '\\.t$'], 'confidence': 75},
    {'name': 'Haskell', 'category': 'language', 'patterns': ['\\.hs$', '\\.lhs$', 'stack\\.yaml', '\\.cabal$'], 'confidence': 75},
    {'name': 'Groovy', 'category': 'language', 'patterns': ['\\.groovy$', '\\.gvy$', '\\.gy$'], 'confidence': 75},
    {'name': 'Elixir', 'category': 'language', 'patterns': ['\\.ex$', '\\.exs$', 'mix\\.exs'], 'confidence': 75},
    {'name': 'Clojure', 'category': 'language', 'patterns': ['\\.clj$', '\\.cljs$', '\\.cljc$', 'project\\.clj'], 'confidence': 75},
    {'name': 'Erlang', 'category': 'language', 'patterns': ['\\.erl$', '\\.hrl$', 'rebar\\.config', 'Emakefile'], 'confidence': 75},
    {'name': 'Fortran', 'category': 'language', 'patterns': ['\\.f$', '\\.for$', '\\.f90$', '\\.f95$', '\\.f03$', '\\.f08$'], 'confidence': 70},
    {'name': 'COBOL', 'category': 'language', 'patterns': ['\\.cob$', '\\.cbl$', '\\.cpy$'], 'confidence': 70},
    {'name': 'Pascal', 'category': 'language', 'patterns': ['\\.pas$', '\\.pp$', '\\.inc$'], 'confidence': 70},
    {'name': 'Ada', 'category': 'language', 'patterns': ['\\.ada$', '\\.adb$', '\\.ads$'], 'confidence': 70},
    {'name': 'Zig', 'category': 'language', 'patterns': ['\\.zig$', 'build\\.zig'], 'confidence': 75},
    {'name': 'Nim', 'category': 'language', 'patterns': ['\\.nim$', '\\.nims$', '\\.nimble$'], 'confidence': 70},
    {'name': 'OCaml', 'category': 'language', 'patterns': ['\\.ml$', '\\.mli$', 'dune-project', 'opam'], 'confidence': 70},
    {'name': 'F#', 'category': 'language', 'patterns': ['\\.fs$', '\\.fsx$', '\\.fsproj$'], 'confidence': 75},
    {'name': 'Crystal', 'category': 'language', 'patterns': ['\\.cr$', 'shard\\.yml'], 'confidence': 70},
    {'name': 'Solidity', 'category': 'language', 'patterns': ['\\.sol$'], 'confidence': 75},
    {'name': 'GraphQL', 'category': 'language', 'patterns': ['\\.graphql$', '\\.gql$', 'schema\\.graphql'], 'confidence': 75},
    {'name': 'YAML', 'category': 'language', 'patterns': ['\\.yml$', '\\.yaml$'], 'confidence': 60},
    {'name': 'TOML', 'category': 'language', 'patterns': ['\\.toml$'], 'confidence': 60},
    {'name': 'Markdown', 'category': 'language', 'patterns': ['\\.md$', '\\.mdx$', '\\.markdown$'], 'confidence': 55},
    {'name': 'Dockerfile', 'category': 'language', 'patterns': ['Dockerfile'], 'confidence': 60},
    {'name': 'Makefile', 'category': 'language', 'patterns': ['Makefile', 'makefile', 'GNUmakefile'], 'confidence': 60},
    {'name': 'React', 'category': 'framework', 'patterns': ['react', 'react-dom', 'create-react-app', 'next\\.config'], 'confidence': 90},
    {'name': 'Next.js', 'category': 'framework', 'patterns': ['next', 'next\\.config\\.(js|ts|mjs)', 'create-next-app'], 'confidence': 90},
    {'name': 'Nuxt.js', 'category': 'framework', 'patterns': ['nuxt', 'nuxt\\.config', 'nuxt3'], 'confidence': 85},
    {'name': 'Vue.js', 'category': 'framework', 'patterns': ['vue', '@vue/', 'vue\\.config\\.js'], 'confidence': 90},
    {'name': 'Angular', 'category': 'framework', 'patterns': ['@angular/', 'angular\\.json'], 'confidence': 90},
    {'name': 'Express.js', 'category': 'framework', 'patterns': ['express'], 'confidence': 85},
    {'name': 'Django', 'category': 'framework', 'patterns': ['django', 'settings\\.py', 'urls\\.py', 'wsgi\\.py', 'asgi\\.py', 'manage\\.py', 'admin\\.py'], 'confidence': 85},
    {'name': 'Flask', 'category': 'framework', 'patterns': ['flask'], 'confidence': 85},
    {'name': 'Spring Boot', 'category': 'framework', 'patterns': ['spring-boot', 'application\\.properties', 'application\\.yml'], 'confidence': 85},
    {'name': 'Ruby on Rails', 'category': 'framework', 'patterns': ['rails', 'Gemfile', 'app/controllers', 'app/models', 'config/routes'], 'confidence': 85},
    {'name': 'Laravel', 'category': 'framework', 'patterns': ['laravel', 'artisan'], 'confidence': 85},
    {'name': 'ASP.NET', 'category': 'framework', 'patterns': ['aspnet', '\\.cshtml$', '\\.vbhtml$', 'Startup\\.cs', 'Program\\.cs'], 'confidence': 80},
    {'name': 'FastAPI', 'category': 'framework', 'patterns': ['fastapi', 'main\\.py'], 'confidence': 85},
    {'name': 'NestJS', 'category': 'framework', 'patterns': ['@nestjs/', 'nest-cli\\.json'], 'confidence': 85},
    {'name': 'Svelte', 'category': 'framework', 'patterns': ['svelte', 'sveltekit', '\\.svelte$'], 'confidence': 85},
    {'name': 'Tailwind CSS', 'category': 'framework', 'patterns': ['tailwindcss', 'tailwind\\.config', '\\.tailwind'], 'confidence': 85},
    {'name': 'Bootstrap', 'category': 'framework', 'patterns': ['bootstrap'], 'confidence': 80},
    {'name': 'Material UI', 'category': 'framework', 'patterns': ['@mui/', 'material-ui'], 'confidence': 80},
    {'name': 'PyTorch', 'category': 'framework', 'patterns': ['torch', 'pytorch'], 'confidence': 85},
    {'name': 'TensorFlow', 'category': 'framework', 'patterns': ['tensorflow', 'tf\\.'], 'confidence': 85},
    {'name': 'Jest', 'category': 'framework', 'patterns': ['jest', '\\.test\\.(js|ts|jsx|tsx)$', '\\.spec\\.(js|ts|jsx|tsx)$'], 'confidence': 80},
    {'name': 'Playwright', 'category': 'framework', 'patterns': ['playwright', 'playwright\\.config'], 'confidence': 80},
    {'name': 'Cypress', 'category': 'framework', 'patterns': ['cypress', 'cypress\\.config'], 'confidence': 80},
    {'name': 'Storybook', 'category': 'framework', 'patterns': ['storybook', '\\.stories\\.(js|ts|jsx|tsx)$'], 'confidence': 80},
    {'name': 'jQuery', 'category': 'framework', 'patterns': ['jquery', 'jquery-ui'], 'confidence': 75},
    {'name': 'HTMX', 'category': 'framework', 'patterns': ['htmx'], 'confidence': 75},
    {'name': 'Alpine.js', 'category': 'framework', 'patterns': ['alpinejs'], 'confidence': 75},
    {'name': 'Electron', 'category': 'framework', 'patterns': ['electron'], 'confidence': 85},
    {'name': 'React Native', 'category': 'framework', 'patterns': ['react-native'], 'confidence': 85},
    {'name': 'Flutter', 'category': 'framework', 'patterns': ['flutter', '\\.dart$'], 'confidence': 85},
    {'name': 'Remix', 'category': 'framework', 'patterns': ['remix', '@remix-run'], 'confidence': 85},
    {'name': 'Gatsby', 'category': 'framework', 'patterns': ['gatsby', 'gatsby-config'], 'confidence': 85},
    {'name': 'Shadcn UI', 'category': 'framework', 'patterns': ['shadcn'], 'confidence': 80},
    {'name': 'Chakra UI', 'category': 'framework', 'patterns': ['@chakra-ui'], 'confidence': 80},
    {'name': 'Ant Design', 'category': 'framework', 'patterns': ['antd', '@ant-design'], 'confidence': 80},
    {'name': 'Redux', 'category': 'framework', 'patterns': ['redux', '@reduxjs/'], 'confidence': 80},
    {'name': 'Zustand', 'category': 'framework', 'patterns': ['zustand'], 'confidence': 75},
    {'name': 'tRPC', 'category': 'framework', 'patterns': ['trpc', '@trpc/'], 'confidence': 80},
    {'name': 'GraphQL', 'category': 'framework', 'patterns': ['graphql', 'apollo', 'graphql-yoga'], 'confidence': 80},
    {'name': 'gRPC', 'category': 'framework', 'patterns': ['grpc', 'protobuf', '\\.proto$'], 'confidence': 75},
    {'name': 'Celery', 'category': 'framework', 'patterns': ['celery'], 'confidence': 80},
    {'name': 'Pandas', 'category': 'framework', 'patterns': ['pandas'], 'confidence': 75},
    {'name': 'NumPy', 'category': 'framework', 'patterns': ['numpy'], 'confidence': 75},
    {'name': 'Scikit-learn', 'category': 'framework', 'patterns': ['scikit-learn', 'sklearn'], 'confidence': 75},
    {'name': 'OpenCV', 'category': 'framework', 'patterns': ['opencv', 'cv2'], 'confidence': 75},
    {'name': 'LangChain', 'category': 'framework', 'patterns': ['langchain', 'langsmith'], 'confidence': 80},
    {'name': 'LlamaIndex', 'category': 'framework', 'patterns': ['llama-index', 'llamaindex'], 'confidence': 80},
    {'name': 'Hugging Face', 'category': 'framework', 'patterns': ['transformers', 'huggingface', 'hugging_face'], 'confidence': 80},
    {'name': 'Streamlit', 'category': 'framework', 'patterns': ['streamlit'], 'confidence': 80},
    {'name': 'Gradio', 'category': 'framework', 'patterns': ['gradio'], 'confidence': 75},
    {'name': 'PostgreSQL', 'category': 'database', 'patterns': ['postgres', 'pg\\b', 'psycopg2', 'pgvector', '\\.psql$'], 'confidence': 90},
    {'name': 'MongoDB', 'category': 'database', 'patterns': ['mongodb', 'mongoose', 'mongod'], 'confidence': 90},
    {'name': 'MySQL', 'category': 'database', 'patterns': ['mysql', '\\.sql$'], 'confidence': 85},
    {'name': 'MariaDB', 'category': 'database', 'patterns': ['mariadb'], 'confidence': 80},
    {'name': 'Redis', 'category': 'database', 'patterns': ['redis', 'ioredis', 'redis-py'], 'confidence': 85},
    {'name': 'SQLite', 'category': 'database', 'patterns': ['sqlite', 'sqlite3', 'better-sqlite3', '\\.sqlite$', '\\.db$'], 'confidence': 85},
    {'name': 'Elasticsearch', 'category': 'database', 'patterns': ['elasticsearch', '@elastic/'], 'confidence': 80},
    {'name': 'DynamoDB', 'category': 'database', 'patterns': ['dynamodb', 'dynamoose'], 'confidence': 80},
    {'name': 'Firebase', 'category': 'database', 'patterns': ['firebase', 'firestore'], 'confidence': 80},
    {'name': 'Prisma', 'category': 'database', 'patterns': ['prisma', '@prisma/', 'schema\\.prisma'], 'confidence': 85},
    {'name': 'Drizzle', 'category': 'database', 'patterns': ['drizzle-orm', 'drizzle-kit'], 'confidence': 80},
    {'name': 'Cassandra', 'category': 'database', 'patterns': ['cassandra', 'scylla'], 'confidence': 80},
    {'name': 'Neo4j', 'category': 'database', 'patterns': ['neo4j', 'cypher'], 'confidence': 75},
    {'name': 'InfluxDB', 'category': 'database', 'patterns': ['influxdb', 'influx'], 'confidence': 75},
    {'name': 'Supabase', 'category': 'database', 'patterns': ['supabase'], 'confidence': 80},
    {'name': 'PlanetScale', 'category': 'database', 'patterns': ['planetscale'], 'confidence': 75},
    {'name': 'SQL Server', 'category': 'database', 'patterns': ['sqlserver', 'mssql', 'sql-server'], 'confidence': 80},
    {'name': 'Oracle DB', 'category': 'database', 'patterns': ['oracle', 'oracledb'], 'confidence': 75},
    {'name': 'SQLAlchemy', 'category': 'database', 'patterns': ['sqlalchemy'], 'confidence': 75},
    {'name': 'Docker', 'category': 'tool', 'patterns': ['Dockerfile', 'docker-compose\\.yml', '\\.dockerignore'], 'confidence': 95},
    {'name': 'GitHub Actions', 'category': 'tool', 'patterns': ['\\.github/workflows/', 'action\\.yml', 'action\\.yaml'], 'confidence': 95},
    {'name': 'ESLint', 'category': 'tool', 'patterns': ['\\.eslintrc', 'eslint\\.config', '\\.eslint'], 'confidence': 85},
    {'name': 'Prettier', 'category': 'tool', 'patterns': ['\\.prettierrc', 'prettier\\.config', '\\.prettier'], 'confidence': 80},
    {'name': 'Webpack', 'category': 'tool', 'patterns': ['webpack\\.config', 'webpack'], 'confidence': 80},
    {'name': 'Vite', 'category': 'tool', 'patterns': ['vite\\.config', 'vite'], 'confidence': 85},
    {'name': 'Babel', 'category': 'tool', 'patterns': ['babel\\.config', '\\.babelrc', '@babel/'], 'confidence': 80},
    {'name': 'Git', 'category': 'tool', 'patterns': ['\\.gitignore', '\\.gitattributes', '\\.gitmodules'], 'confidence': 95},
    {'name': 'Make', 'category': 'tool', 'patterns': ['Makefile', 'makefile', 'GNUmakefile'], 'confidence': 85},
    {'name': 'Yarn', 'category': 'tool', 'patterns': ['yarn\\.lock', '\\.yarnrc'], 'confidence': 85},
    {'name': 'pnpm', 'category': 'tool', 'patterns': ['pnpm-lock', 'pnpm-workspace'], 'confidence': 85},
    {'name': 'nx', 'category': 'tool', 'patterns': ['nx\\.json', 'workspace\\.json', 'nx'], 'confidence': 80},
    {'name': 'Turborepo', 'category': 'tool', 'patterns': ['turbo\\.json'], 'confidence': 80},
    {'name': 'Husky', 'category': 'tool', 'patterns': ['\\.husky/', 'husky\\.config'], 'confidence': 75},
    {'name': 'Rollup', 'category': 'tool', 'patterns': ['rollup\\.config', 'rollup'], 'confidence': 75},
    {'name': 'esbuild', 'category': 'tool', 'patterns': ['esbuild'], 'confidence': 75},
    {'name': 'Parcel', 'category': 'tool', 'patterns': ['parcel'], 'confidence': 70},
    {'name': 'Sentry', 'category': 'tool', 'patterns': ['sentry', '@sentry/'], 'confidence': 80},
    {'name': 'Prometheus', 'category': 'tool', 'patterns': ['prometheus', 'prom'], 'confidence': 80},
    {'name': 'Grafana', 'category': 'tool', 'patterns': ['grafana'], 'confidence': 80},
    {'name': 'Jenkins', 'category': 'tool', 'patterns': ['Jenkinsfile', 'jenkins'], 'confidence': 80},
    {'name': 'AWS', 'category': 'infrastructure', 'patterns': ['aws', 'amazon', 's3', 'lambda', 'ec2', 'cloudformation', 'boto3'], 'confidence': 85},
    {'name': 'Azure', 'category': 'infrastructure', 'patterns': ['azure', 'azurerm'], 'confidence': 85},
    {'name': 'GCP', 'category': 'infrastructure', 'patterns': ['gcp', 'google-cloud', 'gcloud', 'google\\.cloud'], 'confidence': 80},
    {'name': 'Kubernetes', 'category': 'infrastructure', 'patterns': ['kubernetes', 'k8s', 'kube', 'deployment\\.yml', 'deployment\\.yaml'], 'confidence': 85},
    {'name': 'Nginx', 'category': 'infrastructure', 'patterns': ['nginx', 'nginx\\.conf'], 'confidence': 75},
    {'name': 'Cloudflare', 'category': 'infrastructure', 'patterns': ['cloudflare'], 'confidence': 75},
    {'name': 'Terraform', 'category': 'infrastructure', 'patterns': ['terraform', '\\.tf$', '\\.tfvars$'], 'confidence': 80},
    {'name': 'Vercel', 'category': 'infrastructure', 'patterns': ['vercel', 'vercel\\.json'], 'confidence': 80},
    {'name': 'Netlify', 'category': 'infrastructure', 'patterns': ['netlify', 'netlify\\.toml'], 'confidence': 80},
    {'name': 'Heroku', 'category': 'infrastructure', 'patterns': ['heroku', 'Procfile'], 'confidence': 75},
    {'name': 'GitHub Pages', 'category': 'infrastructure', 'patterns': ['gh-pages'], 'confidence': 70},
    {'name': 'Ansible', 'category': 'infrastructure', 'patterns': ['ansible', 'playbook\\.yml'], 'confidence': 80},
]

ARCHITECTURE_PATTERNS: list[dict] = [
    {'name': 'Monorepo', 'indicators': ['packages/', 'apps/', 'modules/'], 'description': 'Single codebase deployed as one unit, typically organized in a flat structure.'},
    {'name': 'Microservices', 'indicators': ['services/', 'api-gateway', 'service-registry'], 'description': 'Multiple independent services communicating via APIs, each deployable separately.'},
    {'name': 'MVC', 'indicators': ['controllers/', 'models/', 'views/'], 'description': 'Model-View-Controller pattern separating data, UI, and business logic.'},
    {'name': 'Clean Architecture', 'indicators': ['domain/', 'application/', 'infrastructure/', 'presentation/'], 'description': 'Layered architecture with dependencies pointing inward toward the domain.'},
    {'name': 'Serverless', 'indicators': ['functions/', 'lambdas/', 'serverless'], 'description': 'Event-driven architecture using cloud functions and managed services.'},
    {'name': 'Hexagonal', 'indicators': ['ports/', 'adapters/', 'core/', 'driven/', 'driving/'], 'description': 'Ports and adapters architecture with isolated core business logic.'},
    {'name': 'Event-Driven', 'indicators': ['events/', 'event-bus', 'kafka', 'rabbitmq', 'pub/sub'], 'description': 'Components communicate through asynchronous events and message brokers.'},
    {'name': 'Plugin Architecture', 'indicators': ['plugins/', 'extensions/', 'addons/'], 'description': 'Core system with pluggable extension points for additional functionality.'},
]


def get_tech_database() -> list[dict]:
    return TECH_DATABASE


def get_tech_keywords() -> list[str]:
    return [
        'react', 'vue', 'angular', 'svelte', 'next.js', 'nuxt', 'node.js', 'deno',
        'typescript', 'javascript', 'python', 'rust', 'go', 'golang', 'java', 'kotlin',
        'swift', 'ruby', 'php', 'c++', 'c#', 'dart', 'flutter', 'tensorflow',
        'pytorch', 'docker', 'kubernetes', 'aws', 'gcp', 'azure', 'firebase',
        'graphql', 'rest', 'api', 'grpc', 'websocket', 'redis', 'postgresql',
        'mongodb', 'mysql', 'sqlite', 'elasticsearch', 'kafka', 'rabbitmq',
        'tailwind', 'bootstrap', 'sass', 'less', 'webpack', 'vite', 'esbuild',
        'jest', 'mocha', 'cypress', 'playwright', 'pandas', 'numpy', 'scikit-learn',
        'opencv', 'llm', 'gpt', 'openai', 'langchain', 'hugging face', 'transformers',
        'fastapi', 'django', 'flask', 'spring', 'laravel', 'rails', 'asp.net',
    ]


def get_architecture_patterns() -> list[dict]:
    return ARCHITECTURE_PATTERNS


def get_onboarding_template() -> list[dict]:
    return [
        {'scenario': 'default', 'sections': ['name', 'description', 'setup', 'usage']},
    ]
